on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'graalvm'
          java-version: '21'
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-cleanup: 'on-success'
          validate-wrappers: 'true'
          gradle-version: 'wrapper'
      - name: Build
        run: gradle build
      - name: Test
        run: gradle test
      - name: Publish
        run: gradle jib --image=ghcr.io/phyrone/${{ github.repository }}:${{ github.sha }}
